/*
 * reCMF — Copyright (C) 2026 reCMF contributors. AGPL-3.0-or-later.
 *
 * Codes ported from Gadgetbridge (AGPL-3.0-or-later); see NOTICE.
 */
package dev.recmf.protocol

/**
 * The exercise types the watch can show in its own sport menu.
 *
 * The codes are the watch's. The first two are permanent — the official app does not let
 * them be removed either — and everything else is the user's choice, up to
 * [CmfSettings.MAX_SPORT_TYPES].
 */
enum class CmfActivityType(val code: Byte) {
    INDOOR_RUNNING(0x03),
    OUTDOOR_RUNNING(0x02),
    OUTDOOR_WALKING(0x01),
    INDOOR_WALKING(0x19),
    OUTDOOR_CYCLING(0x05),
    INDOOR_CYCLING(0x72),
    MOUNTAIN_HIKE(0x04),
    HIKING(0x1A),
    CROSS_TRAINER(0x18),
    FREE_TRAINING(0x10),
    STRENGTH_TRAINING(0x13),
    YOGA(0x0F),
    BOXING(0x21),
    ROWER(0x0E),
    DYNAMIC_CYCLE(0x0D),
    STAIR_STEPPER(0x73),
    TREADMILL(0x26),
    KICKBOXING(0x35),
    HIIT(0x5C),
    FITNESS_EXERCISES(0x4E),
    JUMP_ROPING(0x06),
    PILATES(0x2C),
    CROSSFIT(0x74),
    FUNCTIONAL_TRAINING(0x2E),
    PHYSICAL_TRAINING(0x2F),
    TAEKWONDO(0x25),
    TAE_BO(0x50),
    CROSS_COUNTRY_RUNNING(0x1B),
    KARATE(0x29),
    FENCING(0x54),
    CORE_TRAINING(0x4B),
    KENDO(0x75),
    HORIZONTAL_BAR(0x56),
    PARALLEL_BAR(0x57),
    COOLDOWN(0x92.toByte()),
    CROSS_TRAINING(0x2B),
    SIT_UPS(0x11),
    FITNESS_GAMING(0x4D),
    AEROBIC_EXERCISE(0x94.toByte()),
    ROLLING(0x95.toByte()),
    FLEXIBILITY(0x31),
    GYMNASTICS(0x23),
    TRACK_AND_FIELD(0x27),
    PUSH_UPS(0x67),
    BATTLE_ROPE(0x99.toByte()),
    SMITH_MACHINE(0x9A.toByte()),
    PULL_UPS(0x66),
    PLANK(0x68),
    JAVELIN(0x9E.toByte()),
    LONG_JUMP(0x6C),
    HIGH_JUMP(0x6A),
    TRAMPOLINE(0x5F),
    DUMBBELL(0x9F.toByte()),
    BELLY_DANCE(0x76),
    JAZZ_DANCE(0x77),
    LATIN_DANCE(0x33),
    BALLET(0x36),
    STREET_DANCE(0x34),
    ZUMBA(0x9B.toByte()),
    OTHER_DANCE(0x78),
    ROLLER_SKATING(0x58),
    MARTIAL_ARTS(0x38),
    TAI_CHI(0x1F),
    HULA_HOOPING(0x59),
    DISC_SPORTS(0x43),
    DARTS(0x5A),
    ARCHERY(0x30),
    HORSE_RIDING(0x1D),
    KITE_FLYING(0x70),
    SWING(0x71),
    STAIRS(0x15),
    FISHING(0x42),
    HAND_CYCLING(0x96.toByte()),
    MIND_AND_BODY(0x97.toByte()),
    WRESTLING(0x53),
    KABADDI(0x9C.toByte()),
    KARTING(0xA0.toByte()),
    BADMINTON(0x09),
    TABLE_TENNIS(0x0A),
    TENNIS(0x0C),
    BILLIARDS(0x7C),
    BOWLING(0x3B),
    VOLLEYBALL(0x49),
    SHUTTLECOCK(0x20),
    HANDBALL(0x39),
    BASEBALL(0x3A),
    SOFTBALL(0x55),
    CRICKET(0x0B),
    RUGBY(0x44),
    HOCKEY(0x1E),
    SQUASH(0x3C),
    DODGEBALL(0x81.toByte()),
    SOCCER(0x07),
    BASKETBALL(0x08),
    AUSTRALIAN_FOOTBALL(0x37),
    GOLF(0x45),
    PICKLEBALL(0x5B),
    LACROSS(0x98.toByte()),
    SHOT(0x9D.toByte()),
    BEACH_SOCCER(0x7D),
    BEACH_VOLLEYBALL(0x7E),
    GATEBALL(0x7F),
    SEPAK_TAKRAW(0x80.toByte()),
    SAILING(0x82.toByte()),
    SURFING(0x64),
    JET_SKIING(0x87.toByte()),
    SKATING(0x4C),
    ICE_HOCKEY(0x24),
    CURLING(0x3D),
    SNOWBOARDING(0x3E),
    CROSS_COUNTRY_SKIING(0x6E),
    SNOW_SPORTS(0x48),
    SKIING(0x22),
    LUGE(0x8A.toByte()),
    SKATEBOARDING(0x60),
    ROCK_CLIMBING(0x69),
    HUNTING(0x93.toByte()),
    PARACHUTING(0x8E.toByte()),
    AUTO_RACING(0x8F.toByte()),
    PARKOUR(0x62),
    ;

    companion object {
        /** What the watch ships with, and what reCMF falls back to if nothing is chosen. */
        val DEFAULT: List<CmfActivityType> = listOf(OUTDOOR_RUNNING, INDOOR_RUNNING)

        fun fromCode(code: Byte): CmfActivityType? = entries.firstOrNull { it.code == code }
    }
}
